'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { RoomType, Question } from '@/types'
import { ROOM_TYPES, CADENCE_OPTIONS } from '@/constants'
import { useUser } from '@/hooks/useUser'
import { ArrowLeft, Check, GripVertical, Plus, ShieldCheck, Trash2 } from 'lucide-react'

const labels: Record<string,string> = { pulse_check:'Pulse Check', open_feedback:'Open Feedback', qa:'Q&A', decision_vote:'Decision Vote', hot_take:'Hot Take' }

export default function CreateRoomPage() {
  const router = useRouter(); const { user } = useUser()
  const [step,setStep]=useState(1); const [selectedType,setSelectedType]=useState<RoomType>('pulse_check'); const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [closesAt,setClosesAt]=useState(''); const [recurring,setRecurring]=useState(false); const [cadence,setCadence]=useState('weekly'); const [maxParticipants,setMaxParticipants]=useState(''); const [questions,setQuestions]=useState([{room_id:'',text:'',order_index:0}]); const [loading,setLoading]=useState(false); const [error,setError]=useState('')
  const updateQ=(i:number,text:string)=>setQuestions(q=>q.map((x,n)=>n===i?{...x,text}:x)); const addQ=()=>questions.length<10&&setQuestions(q=>[...q,{room_id:'',text:'',order_index:q.length}]); const removeQ=(i:number)=>questions.length>1&&setQuestions(q=>q.filter((_,n)=>n!==i))
  const next=()=>{setError(''); if(step===1)setStep(2); else if(step===2){if(!name.trim()){setError('Give your room a name first.');return}setStep(3)}else if(step===3){if(!questions.some(q=>q.text.trim())){setError('Add at least one question.');return}setStep(4)}}
  const submit=async()=>{setLoading(true);try{if(!user)throw new Error('You must be logged in to create a room');const response=await fetch('/api/rooms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({room:{name,description,type:selectedType,status:'open',is_recurring:recurring,closes_at:closesAt?new Date(closesAt).toISOString():null,max_participants:maxParticipants?Number(maxParticipants):null},questions:questions.filter(q=>q.text.trim()).map((q,i)=>({...q,order_index:i}))})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Failed to create room');router.push(`/room/${data.id}/results`)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
  return <main className="min-h-screen bg-background px-4 py-8"><div className="mx-auto max-w-2xl motion-enter"><button onClick={()=>router.push('/dashboard')} className="mb-10 inline-flex min-h-11 items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft data-icon="inline-start"/>Back to dashboard</button><div className="mb-8"><p className="eyebrow text-primary">Create something honest</p><h1 className="mt-3 font-serif text-4xl text-foreground">Make room <em>for the real stuff.</em></h1><p className="mt-3 text-muted-foreground">Step {step} of 4 — {['Choose a format','Name your room','Add questions','Review & launch'][step-1]}</p></div><div className="mb-10 flex items-center gap-2">{[1,2,3,4].map(n=><div key={n} className="flex flex-1 items-center gap-2"><div className={`size-3 rounded-full ${n<step?'bg-secondary':n===step?'bg-primary':'bg-border'}`}/>{n<4&&<div className={`h-1 flex-1 rounded-full ${n<step?'bg-secondary':'bg-border'}`}/>}</div>)}</div>{error&&<div role="alert" className="mb-5 rounded-2xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive">{error}</div>}
  {step===1&&<section><h2 className="font-serif text-2xl">What kind of room is this?</h2><p className="mt-2 text-muted-foreground">Each format sets a different tone.</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{ROOM_TYPES.map(t=><button key={t.value} type="button" onClick={()=>setSelectedType(t.value)} className={`relative min-h-36 rounded-2xl border p-5 text-left transition duration-200 hover:-translate-y-1 hover:border-primary/50 ${selectedType===t.value?'border-l-4 border-l-primary border-primary/40 bg-primary/10 shadow-warm':'border-border bg-card'}`}><span className="text-2xl">{t.icon}</span><span className="mt-4 block font-serif text-xl">{t.label}</span><span className="mt-1 block text-sm text-muted-foreground">{t.description}</span>{selectedType===t.value&&<Check className="absolute right-4 top-4 text-primary"/>}</button>)}</div></section>}
  {step===2&&<section className="flex flex-col gap-5"><h2 className="font-serif text-2xl">Give it a name.</h2><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Sprint 12 Retro" className="warm-input text-lg"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="What is this room about? (optional)" rows={4} className="warm-input resize-none"/><label className="text-sm font-medium">Close date <input type="datetime-local" value={closesAt} onChange={e=>setClosesAt(e.target.value)} className="warm-input mt-2"/></label><label className="flex min-h-14 items-center justify-between rounded-2xl border border-border bg-card p-4">Recurring room <input type="checkbox" checked={recurring} onChange={e=>setRecurring(e.target.checked)} className="accent-primary"/></label>{recurring&&<div className="flex gap-2">{CADENCE_OPTIONS.map(c=><button type="button" key={c} onClick={()=>setCadence(c)} className={`rounded-full border px-4 py-2 text-sm ${cadence===c?'bg-foreground text-background':'border-border bg-card'}`}>{c}</button>)}</div>}<label className="text-sm font-medium">Max participants (optional)<input type="number" min="1" value={maxParticipants} onChange={e=>setMaxParticipants(e.target.value)} className="warm-input mt-2" placeholder="Unlimited"/></label></section>}
  {step===3&&<section><h2 className="font-serif text-2xl">What do you want to know?</h2><p className="mt-2 text-muted-foreground">Your team will answer these one at a time.</p><div className="mt-6 flex flex-col gap-3">{questions.map((q,i)=><div key={i} className="rounded-2xl border border-border bg-card p-4"><div className="flex items-start gap-3"><GripVertical className="mt-3 text-muted-foreground"/><span className="rounded-full bg-secondary/15 px-2 py-1 text-xs text-secondary">{i+1}</span><textarea value={q.text} onChange={e=>updateQ(i,e.target.value)} maxLength={500} rows={2} placeholder={`Question ${i+1}`} className="warm-input flex-1 resize-none"/>{questions.length>1&&<button type="button" onClick={()=>removeQ(i)} className="min-h-11 min-w-11 text-muted-foreground hover:text-destructive"><Trash2/></button>}</div><p className="mt-2 text-right text-xs text-muted-foreground">{q.text.length} / 500</p></div>)}</div><button type="button" onClick={addQ} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-full border border-secondary px-5 text-sm text-secondary"><Plus/>Add another question</button><p className="mt-3 text-xs text-muted-foreground">Up to 10 questions</p></section>}
  {step===4&&<section><h2 className="font-serif text-3xl">Ready to open the room?</h2><div className="mt-6 rounded-2xl border border-border bg-card p-6"><span className="room-badge">{labels[selectedType]}</span><h3 className="mt-5 font-serif text-3xl">{name}</h3><p className="mt-2 text-muted-foreground">{description||'A space for honest responses.'}</p><div className="mt-6 flex flex-col gap-2 text-sm text-muted-foreground"><span>{questions.filter(q=>q.text.trim()).length} questions</span><span>{closesAt?`Closes ${new Date(closesAt).toLocaleString()}`:'No closing date'}</span><span>{recurring?`Repeats ${cadence}`:'One-time room'}</span></div></div><div className="mt-5 flex items-center gap-3 rounded-2xl bg-primary/10 p-4 text-sm"><ShieldCheck className="text-primary"/>Anonymous by design — no names, no tracking.</div></section>}
  <div className="mt-10 flex justify-between border-t border-border pt-6">{step>1?<button type="button" onClick={()=>setStep(step-1)} className="min-h-11 rounded-full px-5 text-muted-foreground">← Back</button>:<span/>}{step<4?<button type="button" onClick={next} className="primary-button">Next →</button>:<button type="button" onClick={submit} disabled={loading} className="primary-button w-full sm:w-auto">{loading?'Launching…':'Launch room →'}</button>}</div></div></main>
}
