import Link from 'next/link'
import { Logo } from '@/components/shared'

export default function AboutPage() {
  return <main className="narrow page-content">
    <header className="flex items-center justify-between gap-4"><Link href="/"><Logo /></Link><Link className="text-button" href="/">Back home</Link></header>
    <section className="intro mt-20"><p className="eyebrow text-primary">About Openly</p><h1 className="mt-4 font-serif text-6xl leading-none tracking-tight">Make room for <em>better conversations.</em></h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-muted-foreground">Openly helps teams hear the truth that gets lost in meetings, surveys, and status updates. We believe candor works best when people feel safe enough to use it.</p></section>
    <section className="mt-16 grid gap-5 md:grid-cols-2"><article className="rounded-2xl border border-border bg-card p-7"><p className="eyebrow text-primary">Our value</p><h2 className="mt-3 font-serif text-3xl">Candor with care</h2><p className="mt-3 leading-relaxed text-muted-foreground">We design for direct feedback without turning honesty into a performance.</p></article><article className="rounded-2xl border border-border bg-card p-7"><p className="eyebrow text-primary">Our value</p><h2 className="mt-3 font-serif text-3xl">Privacy by default</h2><p className="mt-3 leading-relaxed text-muted-foreground">Anonymity is not a setting to discover later. It is the foundation of every room.</p></article><article className="rounded-2xl border border-border bg-card p-7"><p className="eyebrow text-primary">House rule</p><h2 className="mt-3 font-serif text-3xl">Assume good intent</h2><p className="mt-3 leading-relaxed text-muted-foreground">Say the useful thing, leave room for context, and treat every response as an invitation to understand.</p></article><article className="rounded-2xl border border-border bg-card p-7"><p className="eyebrow text-primary">House rule</p><h2 className="mt-3 font-serif text-3xl">Make it safer</h2><p className="mt-3 leading-relaxed text-muted-foreground">The goal is not more feedback. It is better conditions for people to tell the truth.</p></article></section>
  </main>
}
