'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'
import { Logo, Pill } from '@/components/shared'

const formats = [
  ['Pulse Check', 'A quick temperature check for the room.'],
  ['Open Feedback', 'Let people say what does not fit in a form.'],
  ['Q&A', 'Ask clearly. Answer safely.'],
  ['Decision Vote', 'See where the real consensus lives.'],
  ['Hot Take', 'Make space for the opinion behind the opinion.'],
]

export default function HomePage() {
  const supabase = createClient()
  const [user, setUser] = useState<any>(null)
  const [annual, setAnnual] = useState(false)
  useEffect(() => { supabase.auth.getUser().then(({ data }) => setUser(data.user)) }, [supabase])
  const startHref = user ? '/room/create' : '/signup'
  return <div className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-40 border-b border-border/70 bg-background/90 px-5 py-4 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between"><Link href="/"><Logo /></Link><nav className="hidden items-center gap-8 text-sm text-muted-foreground md:flex"><a href="#formats" className="hover:text-primary">Formats</a><a href="#how-it-works" className="hover:text-primary">How it works</a><a href="#safety-score" className="hover:text-primary">Safety Score</a></nav><div className="flex items-center gap-3">{user ? <Link className="primary-button" href="/dashboard">Dashboard →</Link> : <><Link className="text-sm text-muted-foreground hover:text-foreground" href="/login">Sign in</Link><Link className="primary-button" href="/signup">Get started free →</Link></>}</div></div></header>
    <main>
      <section className="mx-auto grid min-h-[650px] max-w-7xl items-center gap-14 px-5 py-20 lg:grid-cols-[1.1fr_.9fr]"><div className="motion-enter"><Pill>Anonymous by design</Pill><h1 className="mt-7 max-w-3xl font-serif text-6xl leading-[.94] tracking-tight sm:text-8xl">Say what you <em className="text-primary">really</em> mean.</h1><p className="mt-8 max-w-xl text-lg leading-relaxed text-muted-foreground">A slower, kinder way to collect honest feedback and psychological safety metrics from your team without performance, peer pressure, or fear.</p><div className="mt-8 flex flex-wrap gap-3"><Link href={startHref} className="primary-button px-7">Start a room free →</Link><a href="#demo" className="secondary-button">Try the live survey</a></div><p className="mt-7 text-sm text-muted-foreground">1,200+ teams already speaking freely · no respondent login required</p></div><div id="demo" className="hero-art shadow-warm"><div className="rounded-2xl border border-border bg-card p-7 shadow-warm"><p className="eyebrow text-primary">Sprint retro · Question 1 of 3</p><h2 className="mt-5 font-serif text-3xl">What could we do <em>better?</em></h2><p className="mt-3 text-sm text-muted-foreground">Your answer is 100% anonymous. Take your time.</p><div className="warm-input mt-8 min-h-28 text-sm text-muted-foreground">Say it how you would say it to a friend…</div><div className="mt-6 flex items-center justify-between text-xs"><span>How does this feel?</span><span className="text-primary">Concerning</span></div><div className="mt-3 h-2 rounded-full bg-gradient-to-r from-secondary via-amber-200 to-primary" /></div></div></section>
      <section className="overflow-hidden bg-foreground px-5 py-5 text-background"><div className="marquee-track mx-auto flex w-max items-center gap-10 text-sm"><span className="text-primary">Trusted by teams at</span><span>Northstar</span><span>Fallow</span><span>Arc & Co.</span><span>Kindred</span><span>Fieldwork</span><span>Northstar</span><span>Fallow</span><span>Arc & Co.</span><span>Kindred</span><span>Fieldwork</span></div></section>
      <section className="mx-auto max-w-7xl px-5 py-24"><h2 className="mx-auto max-w-2xl text-center font-serif text-5xl">Most feedback never gets said.</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{['I wanted to tell my manager the deadlines were destroying the team. I said nothing.','Everyone said yes in the meeting. Nobody meant it.','The retro had four people talking and eight people silent.'].map((quote) => <blockquote key={quote} className="rounded-2xl border border-border bg-card p-7 font-serif text-xl italic text-muted-foreground">“{quote}”</blockquote>)}</div><p className="mt-12 text-center font-serif text-4xl text-primary">Openly fixes this.</p></section>
      <section id="formats" className="bg-card px-5 py-24"><div className="mx-auto max-w-7xl"><Pill>Room formats</Pill><h2 className="mt-5 max-w-2xl font-serif text-5xl">Spaces designed for every kind of truth.</h2><div className="mt-10 grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-primary/30 bg-primary/10 p-8 md:col-span-2 md:row-span-2"><p className="eyebrow text-primary">The killer feature</p><h3 className="mt-5 font-serif text-4xl">Two-way anonymous threads</h3><p className="mt-4 max-w-lg text-muted-foreground">Ask a clarifying question on a response without ever exposing who wrote it.</p><div className="mt-12 rounded-2xl bg-foreground p-5 text-background"><p className="text-sm text-background/70">Anonymous responder</p><p className="mt-3">“I think the handoff needs more room.”</p><div className="mt-4 ml-auto max-w-[80%] rounded-xl bg-primary p-3 text-sm">“Thank you for saying it. What would make it easier?”</div></div></article>{formats.map(([title, text]) => <article key={title} className="rounded-2xl border border-border bg-background p-6 transition hover:-translate-y-1 hover:shadow-warm"><h3 className="font-serif text-2xl">{title}</h3><p className="mt-3 text-sm text-muted-foreground">{text}</p></article>)}</div></div></section>
      <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-24"><h2 className="text-center font-serif text-5xl">Honest feedback in 3 quiet steps.</h2><div className="mt-14 grid gap-6 md:grid-cols-3">{[['01','Create your room','Choose a format, add prompts, set a close date.'],['02','Share the link','Send it to Slack, email, or WhatsApp. No sign-up needed.'],['03','Read what they think','Explore sentiment, depth, and anonymous threads.']].map(([n,t,d]) => <article key={n} className="relative rounded-2xl border border-border bg-card p-8"><span className="absolute right-5 top-2 font-serif text-8xl text-primary/10">{n}</span><h3 className="relative font-serif text-2xl">{t}</h3><p className="relative mt-4 text-muted-foreground">{d}</p></article>)}</div></section>
      <section id="safety-score" className="bg-foreground px-5 py-24 text-background"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2"><div><p className="eyebrow text-secondary">Proprietary trust metrics</p><h2 className="mt-5 font-serif text-5xl">Measuring safety without compromising individuals.</h2><p className="mt-5 max-w-xl leading-relaxed text-background/70">Response depth, participation, and thread engagement become one useful signal—never an individual score.</p></div><div className="rounded-2xl border border-background/15 bg-background/5 p-10 text-center"><p className="eyebrow text-secondary">A lit space this week</p><p className="mt-4 font-serif text-8xl text-primary">84</p><p className="mt-5 font-serif text-2xl italic">“We finally hear the quiet people.”</p><p className="mt-3 text-sm text-background/60">— Maya, Head of People at Northstar</p></div></div></section>
      <section className="mx-auto max-w-5xl px-5 py-24 text-center"><h2 className="font-serif text-5xl">Simple pricing. No surprises.</h2><p className="mt-3 text-muted-foreground">Free forever for small teams.</p><div className="mt-6 inline-flex rounded-full border border-border bg-card p-1 text-sm"><button onClick={() => setAnnual(false)} className={`rounded-full px-4 py-2 ${!annual ? 'bg-foreground text-background' : ''}`}>Monthly</button><button onClick={() => setAnnual(true)} className={`rounded-full px-4 py-2 ${annual ? 'bg-foreground text-background' : ''}`}>Annual · save 20%</button></div><div className="mt-10 grid gap-5 text-left md:grid-cols-3">{[['Free','Free forever','3 rooms · 15 responders'],['Pro',annual ? '$86/yr' : '$9/mo','Unlimited rooms · threads'],['Team',annual ? '$230/yr' : '$24/mo','Multiple creators · comparisons']].map(([name,price,features], i) => <article key={name} className={`rounded-2xl border p-7 ${i===1 ? 'border-primary bg-foreground text-background' : 'border-border bg-card'}`}><h3 className="font-serif text-3xl">{name}</h3><p className="mt-5 font-serif text-4xl">{price}</p><p className="mt-4 text-sm opacity-70">{features}</p><Link href={startHref} className="mt-8 inline-flex min-h-11 items-center rounded-full border border-current px-5 text-sm">Choose {name} →</Link></article>)}</div></section>
      <section className="relative overflow-hidden bg-primary px-5 py-24 text-center"><p className="absolute inset-x-0 top-3 text-[9rem] font-serif text-primary-foreground/10">openly.</p><h2 className="relative font-serif text-6xl text-primary-foreground">Your team has things to say.</h2><p className="relative mt-4 text-primary-foreground/80">Give them a safe place to say it.</p><Link href={startHref} className="relative mt-8 inline-flex rounded-full bg-foreground px-7 py-4 text-background">Create your first room — it&apos;s free</Link></section>
    </main><footer className="bg-foreground px-5 py-12 text-background"><div className="mx-auto flex max-w-7xl flex-wrap justify-between gap-8"><div><Logo /><p className="mt-3 max-w-xs text-sm text-background/60">A room for the thoughts that matter.</p></div><div className="flex gap-10 text-sm text-background/70"><a href="#formats">Product</a><a href="#how-it-works">How it works</a><Link href="/privacy">Privacy & anonymity</Link><Link href="/about">About Openly</Link></div></div></footer>
  </div>
}
